# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0

- task: TerraformCLI@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmUseCliFlagsForAuthentication: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_piblic_key=$(publickey.secureFilePath)'
    backendAzureRmUseIdTokenGeneration: true
    backendServiceArm: 'sc-azure-resourcemanager'
    backendAzureRmResourceGroupName: 'rg-akas-terraform-01'
    backendAzureRmStorageAccountName: 'staksterraform001'
    backendAzureRmContainerName: 'container1'
    backendAzureRmKey: 'kubernetes-dev.tfstate'

