trigger:
  branches:
    include:
      - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest

    steps:
    # ✅ Say Hello
    - task: CmdLine@2
      displayName: 'Hello Message'
      inputs:
        script: echo "🚀 Hello Terraform AKS!"

    # ✅ Install Terraform manually
    - script: |
        curl --retry 3 --connect-timeout 10 --max-time 60 --location --fail \
          https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip \
          -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        chmod +x /usr/local/bin/terraform
        terraform version
      displayName: 'Install Terraform 1.5.7'

    # ✅ Download SSH key
    - task: DownloadSecureFile@1
      name: publickey
      inputs:
        secureFile: 'azure_rsa.pub'

    # ✅ Terraform Init
    - script: |
        cd $(System.DefaultWorkingDirectory)

        terraform init \
          -backend-config="resource_group_name=rg-akas-terraform-01" \
          -backend-config="storage_account_name=staksterraform001" \
          -backend-config="container_name=container1" \
          -backend-config="key=kubernetes-dev.tfstate" \
          -backend-config="subscription_id=ee319277-edaa-4c07-9b91-04d1eb7bf895" \
          -backend-config="tenant_id=d5d40ca8-b5aa-4d8f-8272-407b515cb5a7"
      displayName: 'Terraform Init'


    # ✅ Terraform Apply
    - script: |
        cd $(System.DefaultWorkingDirectory)

        terraform apply -auto-approve \
          -var="client_id=$(client_id)" \
          -var="client_secret=$(client_secret)" \
          -var="ssh_public_key=$(publickey.secureFilePath)"
      displayName: 'Terraform Apply (Creates Infrastructure)'
